#!/usr/bin/perl -w

use strict;
use LWP::UserAgent;
use HTTP::Request::Common;

my $username = $ARGV[ 0 ];
if ( not defined $username ) {
  die "Usage: $0 USERNAME\n";
}

my $receiver_pid = fork;

if ( $receiver_pid < 0 ) {
  die qq{$!};
} elsif ( $receiver_pid == 0 ) {
  # child
  exec q{./receiver 9090} or die qq{$!};
}

chomp( my $prefix = qx{dirname `which mm-link`} );
my $tracedir = $prefix . q{/../share/mahimahi/traces};

# run the sender inside a linkshell and a delayshell
my @command = qw{mm-delay 20 mm-loss uplink 0.01 mm-link UPLINK DOWNLINK};

# display livegraphs if we seem to be running under X
if ( defined $ENV{ 'DISPLAY' } ) {
  push @command, qw{--meter-uplink --meter-uplink-delay};
}

push @command, qw{--once --uplink-log=./contest_uplink_log --uplink-queue=droptail --uplink-queue-args="bytes=64000" -- bash -c};

push @command, q{./sender $MAHIMAHI_BASE 9090};

# for the contest, we will send data over Verizon's downlink
# (datagrump sender's uplink)
die unless $command[ 6 ] eq "UPLINK";
$command[ 6 ] = qq{$tracedir/Verizon-LTE-short.down};

die unless $command[ 7 ] eq "DOWNLINK";
$command[ 7 ] = qq{$tracedir/Verizon-LTE-short.up};

system @command;

# kill the receiver
kill 'INT', $receiver_pid;

print "\n";

print qq{ done.\n\n};


print "\n";
